import { countFolders, getProjectTypeLabel } from "../data/pipelineTemplates.js";

const INVALID_FOLDER_CHARS = /[<>:"/\\|?*\u0000-\u001F]/g;

export function sanitizeProjectName(value) {
  return value
    .trim()
    .replace(INVALID_FOLDER_CHARS, "-")
    .replace(/\s+/g, " ")
    .replace(/[. ]+$/g, "")
    .slice(0, 120);
}

export function isFileSystemAccessSupported() {
  return typeof window !== "undefined" && "showDirectoryPicker" in window;
}

export function buildFolderReadme({
  projectName,
  projectType,
  relativePath,
  description,
}) {
  const typeLabel = getProjectTypeLabel(projectType);
  const folderName = relativePath.split("/").at(-1) ?? projectName;

  return `# ${folderName}

**Project:** ${projectName}  
**Pipeline:** ${typeLabel}  
**Path:** ${relativePath}

## Purpose

${description}

## Working rules

- Store only files that belong to this folder's production purpose.
- Keep previous versions and increase version numbers sequentially.
- Use three-digit shot IDs such as \`sc001\` for shot-based work.
- Keep temporary, review, and approved outputs clearly separated.

## Naming pattern

\`${projectName.replace(/\s+/g, "_")}_${folderName}_v01\`

---

Generated by [AnimFlow](https://github.com/BoooombKid/AnimFlow) — Animation Pipeline Builder.
`;
}

async function writeTextFile(directoryHandle, fileName, contents) {
  const fileHandle = await directoryHandle.getFileHandle(fileName, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(contents);
  await writable.close();
}

async function directoryExists(parentHandle, name) {
  try {
    await parentHandle.getDirectoryHandle(name);
    return true;
  } catch (error) {
    if (error?.name === "NotFoundError") return false;
    throw error;
  }
}

async function createNodes({
  parentHandle,
  nodes,
  projectName,
  projectType,
  parentPath,
  progress,
}) {
  for (const node of nodes) {
    const childHandle = await parentHandle.getDirectoryHandle(node.name, { create: true });
    const relativePath = `${parentPath}/${node.name}`;
    await writeTextFile(
      childHandle,
      "README.md",
      buildFolderReadme({
        projectName,
        projectType,
        relativePath,
        description: node.description,
      }),
    );
    progress.completed += 1;
    progress.onProgress?.({ ...progress, current: relativePath });

    await createNodes({
      parentHandle: childHandle,
      nodes: node.children,
      projectName,
      projectType,
      parentPath: relativePath,
      progress,
    });
  }
}

export async function createProjectStructure({
  destinationHandle,
  projectName,
  projectType,
  pipeline,
  onProgress,
}) {
  const safeProjectName = sanitizeProjectName(projectName);
  if (!safeProjectName) {
    throw new Error("Enter a valid project name.");
  }

  if (await directoryExists(destinationHandle, safeProjectName)) {
    throw new Error(
      `A folder named “${safeProjectName}” already exists in this destination.`,
    );
  }

  const projectHandle = await destinationHandle.getDirectoryHandle(safeProjectName, {
    create: true,
  });
  const total = countFolders(pipeline) + 1;
  const progress = { completed: 0, total, onProgress };

  await writeTextFile(
    projectHandle,
    "README.md",
    buildFolderReadme({
      projectName: safeProjectName,
      projectType,
      relativePath: safeProjectName,
      description:
        "Project root containing the complete production pipeline and shared project documentation.",
    }),
  );
  progress.completed += 1;
  onProgress?.({ ...progress, current: safeProjectName });

  await createNodes({
    parentHandle: projectHandle,
    nodes: pipeline,
    projectName: safeProjectName,
    projectType,
    parentPath: safeProjectName,
    progress,
  });

  return {
    projectName: safeProjectName,
    foldersCreated: total,
  };
}
